### ISSUE TITLE
kotaemon rag framework?

### ISSUE THREAD

**Issue by djl0** [Andrew-Jang/RAGHub#36]
I'm curious where [kotaemon](https://github.com/Cinnamon/kotaemon) fits into this. Seems like "RAG Projects". I didn't want to jump to adding it to the list, but is anyone using it and can comment? Currently has more than 14k stars, so it seems substantial.

**Comment by Andrew-Jang** [comment]
"RAG Projects" will do. Please add it to the list! 
I'm later planning to add "Document/Files" category (as seen in raghut.com).
